-- Generated from funnel-schema.js. Existing version definitions are immutable.
begin;
insert into public.relustt_quiz_definitions(quiz_version,step_id,sort_order,label,answer_key,tags) values
('relustt-2026-09-20-v1','welcome',0,'Welcome',null,array['information','shared']),
('relustt-2026-09-20-v1','frequency',1,'Viewing frequency','frequency',array['question','shared']),
('relustt-2026-09-20-v1','motivation',2,'Main motivation','motivation',array['question','shared']),
('relustt-2026-09-20-v1','quit-history',3,'Previous attempts','triedQuit',array['question','shared']),
('relustt-2026-09-20-v1','quit-progress',4,'Progress so far','quitProgress',array['question','conditional']),
('relustt-2026-09-20-v1','quit-feedback',5,'Quit feedback',null,array['information','shared']),
('relustt-2026-09-20-v1','urge-context',6,'Urge context','urgeContext',array['question','shared']),
('relustt-2026-09-20-v1','obstacles',7,'Main obstacle','obstacle',array['question','shared']),
('relustt-2026-09-20-v1','build-your-system',8,'Obstacle insight',null,array['information','shared']),
('relustt-2026-09-20-v1','personalizing',9,'Personalizing',null,array['information','shared']),
('relustt-2026-09-20-v1','watch-control',10,'Watching longer than intended','watchControl',array['question','shared']),
('relustt-2026-09-20-v1','main-priority',11,'Main priority','changePriority',array['question','shared']),
('relustt-2026-09-20-v1','intimacy',12,'Intimacy experience','forkAnswer',array['question','shared']),
('relustt-2026-09-20-v1','intimacy-concern',13,'Intimacy concern','intimacyConcern',array['question','conditional']),
('relustt-2026-09-20-v1','intimacy-worry',14,'Reassurance',null,array['information','conditional']),
('relustt-2026-09-20-v1','brain-conditioning',15,'Brain conditioning',null,array['information','performance']),
('relustt-2026-09-20-v1','performance-content-intensity',16,'Content intensity','contentIntensity',array['question','performance']),
('relustt-2026-09-20-v1','arousal-threshold',17,'Arousal threshold',null,array['information','performance']),
('relustt-2026-09-20-v1','setback-trigger',18,'Setback trigger','setbackTrigger',array['question','conditional']),
('relustt-2026-09-20-v1','support-preference',19,'Preferred support','supportPreference',array['question','shared']),
('relustt-2026-09-20-v1','good-news',20,'Support introduction',null,array['information','shared']),
('relustt-2026-09-20-v1','your-support',21,'Support feature',null,array['information','shared']),
('relustt-2026-09-20-v1','one-more-thing',22,'Blocker introduction bridge',null,array['information','shared']),
('relustt-2026-09-20-v1','blocker-introduction',23,'Blocking preview',null,array['information','shared']),
('relustt-2026-09-20-v1','safe-word',24,'Safe word setup (value excluded)',null,array['information','shared']),
('relustt-2026-09-20-v1','blocker-ready',25,'Blocker ready',null,array['information','shared']),
('relustt-2026-09-20-v1','blocker-reminder',26,'Blocker reminder',null,array['information','shared']),
('relustt-2026-09-20-v1','performance-commitment',27,'Commitment','commitment',array['question','performance']),
('relustt-2026-09-20-v1','identity-commitment',28,'Commitment','commitment',array['question','shared']),
('relustt-2026-09-20-v1','your-name',29,'Name','name',array['question','shared']),
('relustt-2026-09-20-v1','pledge',30,'Vow (signature excluded)',null,array['information','shared']),
('relustt-2026-09-20-v1','analyzing-answers',31,'Analysis',null,array['information','shared']),
('relustt-2026-09-20-v1','choose-price',32,'Trial price','selectedPrice',array['question','shared','offer']),
('relustt-2026-09-20-v1','your-plan',33,'Personal offer',null,array['information','shared','offer'])
on conflict do nothing;
commit;
